on: [push, pull_request]

permissions:
  contents: read

jobs:
  server:
    uses: ./.github/workflows/server-ci.yml

  plugin:
    uses: ./.github/workflows/plugin-ci.yml

  summary:
    name: Publish reports
    if: ${{ always() && !cancelled() }}
    needs:
      - server
      - plugin
    uses: ./.github/workflows/ci-summary.yml
